#pragma once

/// @file codegen.hpp
/// @brief DSL-002 Code Generator - Linear IR to bytecode emission
///
/// Converts LinearIR to DotVM bytecode:
/// - Instruction selection from IR ops to opcodes
/// - Jump offset calculation
/// - Bytecode assembly with constant pool

#include <cstdint>
#include <expected>
#include <string>
#include <vector>

#include "dotvm/core/bytecode.hpp"
#include "dotvm/core/dsl/compiler/lowerer.hpp"
#include "dotvm/core/opcode.hpp"

namespace dotvm::core::dsl::compiler {

/// @brief Error during code generation
struct CodegenError {
    enum class Kind {
        UnsupportedInstruction,
        ConstantPoolOverflow,
        JumpOutOfRange,
        InternalError,
    };

    Kind kind;
    std::string message;

    static CodegenError unsupported(const std::string& msg) {
        return CodegenError{Kind::UnsupportedInstruction, msg};
    }

    static CodegenError overflow(const std::string& msg) {
        return CodegenError{Kind::ConstantPoolOverflow, msg};
    }

    static CodegenError jump_range(const std::string& msg) {
        return CodegenError{Kind::JumpOutOfRange, msg};
    }

    static CodegenError internal(const std::string& msg) {
        return CodegenError{Kind::InternalError, msg};
    }
};

/// @brief Result type for codegen operations
template <typename T>
using CodegenResult = std::expected<T, CodegenError>;

/// @brief Generated bytecode output
struct GeneratedCode {
    std::vector<std::uint8_t> code;           ///< Bytecode instructions
    std::vector<dotvm::core::Value> constants; ///< Constant pool
    std::uint64_t entry_point{0};             ///< Entry point offset
    Architecture arch{Architecture::Arch64};
};

/// @brief Bytecode generator
class CodeGenerator {
public:
    explicit CodeGenerator(Architecture arch = Architecture::Arch64) : arch_(arch) {}

    /// @brief Generate bytecode from LinearIR
    [[nodiscard]] CodegenResult<GeneratedCode> generate(const LinearIR& ir);

    /// @brief Assemble complete bytecode file
    [[nodiscard]] std::vector<std::uint8_t> assemble(const GeneratedCode& code);

private:
    Architecture arch_;

    // Instruction encoding
    void emit_type_a(std::vector<std::uint8_t>& code, std::uint8_t opcode,
                     std::uint8_t rd, std::uint8_t rs1, std::uint8_t rs2);
    void emit_type_b(std::vector<std::uint8_t>& code, std::uint8_t opcode,
                     std::uint8_t rd, std::int16_t imm);
    void emit_type_c(std::vector<std::uint8_t>& code, std::uint8_t opcode,
                     std::int32_t offset24);
    void emit_type_m(std::vector<std::uint8_t>& code, std::uint8_t opcode,
                     std::uint8_t rd_rs2, std::uint8_t rs1, std::int8_t offset);

    // Constant pool management
    std::uint32_t add_constant(std::vector<dotvm::core::Value>& pool,
                                dotvm::core::Value val);

    // Label resolution
    struct LabelRef {
        std::size_t code_offset;
        std::string label;
        bool is_relative;
    };
    std::vector<LabelRef> pending_labels_;
    std::unordered_map<std::string, std::size_t> label_offsets_;

    void record_label(const std::string& label, std::size_t offset);
    void add_label_ref(std::size_t offset, const std::string& label, bool relative);
    CodegenResult<void> resolve_labels(std::vector<std::uint8_t>& code);

    // Instruction generation
    CodegenResult<void> gen_instruction(const LinearInstr& instr,
                                         std::vector<std::uint8_t>& code,
                                         std::vector<dotvm::core::Value>& constants);
};

}  // namespace dotvm::core::dsl::compiler
